config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

    # Sessions
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users
  resources :trades do
    member do
      put "like", to: "trades#upvote"
      put "dislike", to: "trades#downvote"
    end
  end
end

app/models/FFN.rb
class FFN

  def self.players
    api_key = ENV['FFN_API_KEY']
    ffn_url = "http://www.fantasyfootballnerd.com/service/players/json/#{api_key}"
    api_call = HTTParty.get(ffn_url)["Players"]
  end

end

app/models/package.rb
class Package < ActiveRecord::Base

  belongs_to :trade
  has_and_belongs_to_many :players

end

app/models/player.rb
class Player < ActiveRecord::Base

  has_and_belongs_to_many :packages

  validates :name, :position, :team, presence: true

end

app/models/trade.rb
class Trade < ActiveRecord::Base

  belongs_to :user
  has_many :packages, dependent: :destroy
  acts_as_votable

  accepts_nested_attributes_for :packages

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :trades, dependent: :destroy
  has_secure_password
  acts_as_voter

  validates :first_name, :last_name, presence: true
  validates :username, presence: true,
                       uniqueness: true
  validates :email, presence: true,
                    uniqueness: true
  validates :password, presence: true,
                       length: { minimum: 6,
                                 message: 'must be at least 6 characters'}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    User.find_by(id: session[:current_user]) if session[:current_user]
  end

  def authenticate
    redirect_to login_path unless current_user
  end

  def authorize
    unless current_user && current_user.id == params[:id].to_i
      redirect_to users_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user.authenticate(params[:password])
      session[:current_user] = user.id
      redirect_to trades_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:current_user] = nil
    redirect_to login_path
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController

  before_action :authenticate, only: [:new, :create, :destroy]

  # show random trade
  def index
    @trade = Trade.all.sample
  end

  # show specific trade
  def show
    @trade = Trade.find(params[:id])
  end

  # new trade form
  def new
    @trade = Trade.new
    @trade.user_id = session[:current_user]
    @trade.packages = [Package.new, Package.new]
    @qb = Player.where(position: "QB")
    @rb = Player.where(position: "RB")
    @wr = Player.where(position: "WR")
    @te = Player.where(position: "TE")
    @kicker = Player.where(position: "K")
  end

  # create trade
  def create
    trade = Trade.new
    package1 = package("0")
    package2 = package("1")
    trade.user_id = session[:current_user]
    package1.save
    package2.save
    trade.packages = [package1, package2]
    if trade.save
      redirect_to trade_path(trade)
    else
      render :new
    end
  end

  # vote yes
  def upvote
    @trade = Trade.find(params[:id])
    @trade.up_from current_user
    redirect_to trade_path(@trade)
  end

  # vote no
  def downvote
    @trade = Trade.find(params[:id])
    @trade.down_from current_user
    redirect_to trade_path(@trade)
  end

  #destroys trades
  def destroy
    @trade = Trade.find(params[:id])
    @trade.destroy
    user = user.find(session[:current_user])
    redirect_to user_path(user)
  end

  # creates a package
  def package(index)
    package = Package.new
    params["trade"]["packages_attributes"][index]["players"].each do |id|
      if !id.blank?
        package.players << Player.find(id)
      end
    end
    return package
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:current_user] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username,
                                 :first_name,
                                 :last_name,
                                 :email,
                                 :image_url,
                                 :password,
                                 :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoulditrade</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="login">
  <% if current_user %>
    Welcome back, <%= current_user.first_name %>! |
    <%= link_to 'My Profile', user_path(current_user) %> |
    <%= link_to 'Log Out', logout_path %> |
  <% else %>
    <%= link_to 'Log In', login_path %> |
    <%= link_to 'Sign Up', new_user_path %> |
  <% end %>
  </p>
  <h1><%= link_to('Should I Trade?', trades_path) %></h1>
  <h2><%= link_to('Post a Trade', new_trade_path) %></h2>

<%= yield %>

</body>
</html>

app/views/trades/_form.html.erb
<table>
  <%= form_for @trade do |f| %>
  <tr>
    <th colspan="2">
    </th>
  </tr>
  <tr>

        <%= f.fields_for :packages do |a| %>
        <td>
        <b><%= a.label :players  %></b><br>
        Quarterbacks:<br>
        <%= a.select( :players, options_for_select(@qb.map do |player|
          [player.name, player.id]
        end), {}, {multiple: true, size: 5}) %>
        <br>
        Running Backs:<br>
        <%= a.select( :players, options_for_select(@rb.map do |player|
          [player.name, player.id]
        end), {}, {multiple: true, size: 10}) %>
        <br>
        Wide Receivers:<br>
        <%= a.select( :players, options_for_select(@wr.map do |player|
          [player.name, player.id]
        end), {}, {multiple: true, size: 10}) %>
        <br>
        Tight Ends:<br>
        <%= a.select( :players, options_for_select(@te.map do |player|
          [player.name, player.id]
        end), {}, {multiple: true, size: 4}) %>
        <br>
        Kickers:<br>
        <%= a.select( :players, options_for_select(@kicker.map do |player|
          [player.name, player.id]
        end), {}, {multiple: true, size: 4}) %>
        <br>
        <% end %>
  </tr>
  <tr>
    <th colspan="2">
      <%= f.submit %>
      <% end %>
      <br>
    </th>
  </tr>
</table>

app/views/trades/_players.html.erb
<%= a.select( :players, options_for_select(@qb.map do |player|
  [player.name, player.id]
end), {}, {multiple: true, size: 5}) %>

app/views/trades/_show.html.erb
<table class="trade">
  <tr>
    <% @trade.packages.each do |package| %>
      <td>
        <% package.players.each do |player| %>
          <%= player.position %> - <%= player.name %> - <%= player.team %><br>
        <% end %>
      </td>
    <% end %>
  </tr>
  <tr>
    <th colspan="2">
      <%= link_to image_tag("thumbsup.png"), like_trade_path(@trade), method: :put %>
      <%= link_to image_tag("thumbsdown.png"), dislike_trade_path(@trade), method: :put %>
    </th>
  </tr>
  <tr>
    <th colspan="2">
      Yes - <%= @trade.get_up_votes.size %>
      <br>
      No - <%= @trade.get_down_votes.size %>
    </th>
  </tr>
</table>

app/views/trades/edit.html.erb
<%= render 'form' %>

app/views/trades/index.html.erb
<%= render 'show' %>

app/views/trades/new.html.erb
<%= render 'form' %>

app/views/trades/show.html.erb
<%= render 'show' %>

app/views/users/_form.html.erb
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>

<%= form_for @user do |f| %>
  <%= f.label :username %>:
  <%= f.text_field :username %>
  <br>
  <%= f.label :email %>:
  <%= f.text_field :email %>
  <br>
  <%= f.label :first_name %>:
  <%= f.text_field :first_name %>
  <br>
  <%= f.label :last_name %>:
  <%= f.text_field :last_name %>
  <%= f.hidden_field :image_url, value: "http://lorempixel.com/200/200/sports/" %>:
  <br>
  <%= f.label :password %>:
  <%= f.password_field :password %>(*Must be at least 6 characters)
  <br>
  <%= f.label :password_confirmation %>:
  <%= f.password_field :password_confirmation %>
  <br>

  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h3>Edit Profile</h3>

<%= render 'form' %>


<%= button_to "Delete This Account", user_path(@user), method: :delete, data: {confirm: "Are you sure you want to do that?"} %>

app/views/users/index.html.erb
<h2>current users</h2>

<ul>
<% @users.each do |user| %>
  <li><%= link_to("#{user.username}", user_path(user))%></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h3>Registration</h3>

<%= render 'form' %>

app/views/users/show.html.erb
<h3><%= @user.username %></h3>
<p>
  <%= link_to('Edit profile', edit_user_path(@user)) %>
</p>

<div id="user">
  <ul>
    <li><%= image_tag(@user.image_url) %></li>
    <li>Username: <%= @user.username %></li>
    <li>First Name: <%= @user.first_name.capitalize %></li>
    <li>Last Name: <%= @user.last_name.capitalize %></li>
    <li>Email: <%= @user.email %></li>
    <li>
      <ul>
        My Trades
        <% @user.trades.order('created_at Desc').each do |trade| %>
        <li><%= link_to("#{trade.created_at.strftime("%m/%d/%Y")}", trade_path(trade)) %>
          <%= button_to "Delete", trade_path(trade), method: :delete,
          data: {confirm: "Are you sure you want to do that?"} %></li>
        <% end %>
      </ul>
    </li>
  </ul>
</div>

app/views/welcome/index.html.erb
<p>
  Welcome to 'Should I Trade?'
</p>
<p>
  Have you ever struggled over a trade decision?
  Have you ever wanted to ask the world if you should make a trade?
  Do you want to win your fantasy league this year?
</p>
<ol>
  Well now you can in <em>3 easy steps</em>!
  <li> Sign up! </li>
  <li> Recreate the trade proposal! </li>
  <li> See what the world thinks. </li>
</ol>
<p>
  Also while you wait, feel free to peruse other trades and give your vote. Because every vote you provide, we sponser the fantasy team of a child in a third world country.
  Remember we can only achieve greatness, if we first achieve goodness.
</p>